#!/bin/sh
COMPOSER_ALLOW_SUPERUSER=1 composer install --prefer-dist --no-dev --no-autoloader --no-scripts --no-progress --no-suggest --ignore-platform-reqs &>/dev/null
COMPOSER_ALLOW_SUPERUSER=1 composer show | awk '{ print "comp+"$1"$"$2}' | sort | uniq