#!/bin/sh
tmp=${TMPDIR:-/tmp}/mvn.bom-cli.$$
m2repo=${TMPDIR:-/tmp}/mvn.bom-cli.$$.m2repo
srclibcache=${TMPDIR:-/tmp}/mvn.bom-cli.$$.srclibcache

setup() {
  [ -e .m2-srclib ] && mv .m2-srclib $m2repo
  [ -e .srclib-cache ] && mv .srclib-cache $srclibcache
}

teardown() {
  [ -e $m2repo ] && mv $m2repo .m2-srclib
  [ -e $srclibcache ] && mv $srclibcache .srclib-cache
}

setup;

if mvn clean install -DskipTests -Drat.skip=true &> /dev/null && mvn dependency:list > $tmp; then
  cat $tmp | grep -E "\[INFO\]    .+\:.+\:" -o | sed 's/\[INFO\]    /mvn+/' | sed 's/.$//' | sed 's/:jar:/$/'  | sed 's/:war:/$/'  | sed 's/:java-source:/$/' | sort -u;
  teardown;
else
  teardown;
  exit 1;
fi;